export const CART_REQUEST = "CART_REQUEST";
export const CART_REQUEST_SUCCESS = "CART_REQUEST_SUCCESS";
export const CART_REQUEST_FAILURE = "CART_REQUEST_FAILURE";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_REQUEST_SUCCESS = "ADD_TO_CART_REQUEST_SUCCESS";
export const ADD_TO_CART_REQUEST_FAILURE = "ADD_TO_CART_REQUEST_FAILURE";

export const DELETE_FROM_CART_REQUEST = "DELETE_FROM_CART_REQUEST";
export const DELETE_FROM_CART_REQUEST_SUCCESS = "DELETE_FROM_CART_REQUEST_SUCCESS";
export const DELETE_FROM_CART_REQUEST_FAILURE = "DELETE_FROM_CART_REQUEST_FAILURE";

export const EDIT_CART_REQUEST = "EDIT_CART_REQUEST";
export const EDIT_CART_REQUEST_SUCCESS = "EDIT_CART_REQUEST_SUCCESS";
export const EDIT_CART_REQUEST_FAILURE = "EDIT_CART_REQUEST_FAILURE";
