export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILURE = "PRODUCT_LIST_FAILURE";

export const ADD_EDIT_PRODUCT_REQUEST = "ADD_EDIT_PRODUCT_REQUEST";
export const ADD_EDIT_PRODUCT_REQUEST_SUCCESS = "ADD_EDIT_PRODUCT_REQUEST_SUCCESS";
export const ADD_EDIT_PRODUCT_REQUEST_FAILURE = "ADD_EDIT_PRODUCT_REQUEST_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_REQUEST_SUCCESS = "DELETE_PRODUCT_REQUEST_SUCCESS";
export const DELETE_PRODUCT_REQUEST_FAILURE = "DELETE_PRODUCT_REQUEST_FAILURE";